resources(
    name='compiled-contracts',
    sources=rglobs('compiled-contracts/contracts/*.json'),
    dependencies=[
    ]
)

resources(
    name='configs',
    sources=rglobs('configs/**/*.json'),
    dependencies=[
    ]
)

