// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package neutralservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserAccountInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tier                 string   `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAccountInfo) Reset()         { *m = UserAccountInfo{} }
func (m *UserAccountInfo) String() string { return proto.CompactTextString(m) }
func (*UserAccountInfo) ProtoMessage()    {}
func (*UserAccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *UserAccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountInfo.Unmarshal(m, b)
}
func (m *UserAccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountInfo.Marshal(b, m, deterministic)
}
func (m *UserAccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountInfo.Merge(m, src)
}
func (m *UserAccountInfo) XXX_Size() int {
	return xxx_messageInfo_UserAccountInfo.Size(m)
}
func (m *UserAccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountInfo proto.InternalMessageInfo

func (m *UserAccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAccountInfo) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

type AccountRequest struct {
	UserID               *UserID  `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetUserID() *UserID {
	if m != nil {
		return m.UserID
	}
	return nil
}

type SignedAccountRequest struct {
	Signature            *Signature      `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Wrapped              *AccountRequest `protobuf:"bytes,2,opt,name=wrapped,proto3" json:"wrapped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignedAccountRequest) Reset()         { *m = SignedAccountRequest{} }
func (m *SignedAccountRequest) String() string { return proto.CompactTextString(m) }
func (*SignedAccountRequest) ProtoMessage()    {}
func (*SignedAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *SignedAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAccountRequest.Unmarshal(m, b)
}
func (m *SignedAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAccountRequest.Marshal(b, m, deterministic)
}
func (m *SignedAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAccountRequest.Merge(m, src)
}
func (m *SignedAccountRequest) XXX_Size() int {
	return xxx_messageInfo_SignedAccountRequest.Size(m)
}
func (m *SignedAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAccountRequest proto.InternalMessageInfo

func (m *SignedAccountRequest) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedAccountRequest) GetWrapped() *AccountRequest {
	if m != nil {
		return m.Wrapped
	}
	return nil
}

type AccountInfo struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tier                 string   `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UserID               *UserID  `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	PublicKey            *Pubkey  `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	BidSpread            *Price   `protobuf:"bytes,6,opt,name=bidSpread,proto3" json:"bidSpread,omitempty"`
	AskSpread            *Price   `protobuf:"bytes,7,opt,name=askSpread,proto3" json:"askSpread,omitempty"`
	ExpirationBlocks     uint32   `protobuf:"varint,8,opt,name=expirationBlocks,proto3" json:"expirationBlocks,omitempty"`
	ExpirationTime       uint64   `protobuf:"varint,9,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	MinBidQuantity       float64  `protobuf:"fixed64,10,opt,name=minBidQuantity,proto3" json:"minBidQuantity,omitempty"`
	MaxBidQuantity       float64  `protobuf:"fixed64,11,opt,name=maxBidQuantity,proto3" json:"maxBidQuantity,omitempty"`
	MinAskQuantity       float64  `protobuf:"fixed64,12,opt,name=minAskQuantity,proto3" json:"minAskQuantity,omitempty"`
	MaxAskQuantity       float64  `protobuf:"fixed64,13,opt,name=maxAskQuantity,proto3" json:"maxAskQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AccountInfo) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountInfo) GetUserID() *UserID {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *AccountInfo) GetPublicKey() *Pubkey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AccountInfo) GetBidSpread() *Price {
	if m != nil {
		return m.BidSpread
	}
	return nil
}

func (m *AccountInfo) GetAskSpread() *Price {
	if m != nil {
		return m.AskSpread
	}
	return nil
}

func (m *AccountInfo) GetExpirationBlocks() uint32 {
	if m != nil {
		return m.ExpirationBlocks
	}
	return 0
}

func (m *AccountInfo) GetExpirationTime() uint64 {
	if m != nil {
		return m.ExpirationTime
	}
	return 0
}

func (m *AccountInfo) GetMinBidQuantity() float64 {
	if m != nil {
		return m.MinBidQuantity
	}
	return 0
}

func (m *AccountInfo) GetMaxBidQuantity() float64 {
	if m != nil {
		return m.MaxBidQuantity
	}
	return 0
}

func (m *AccountInfo) GetMinAskQuantity() float64 {
	if m != nil {
		return m.MinAskQuantity
	}
	return 0
}

func (m *AccountInfo) GetMaxAskQuantity() float64 {
	if m != nil {
		return m.MaxAskQuantity
	}
	return 0
}

// Account mapping UUID -> Account
type Accounts struct {
	Accounts             map[string]*AccountInfo `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetAccounts() map[string]*AccountInfo {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*UserAccountInfo)(nil), "neutralservice.UserAccountInfo")
	proto.RegisterType((*AccountRequest)(nil), "neutralservice.AccountRequest")
	proto.RegisterType((*SignedAccountRequest)(nil), "neutralservice.SignedAccountRequest")
	proto.RegisterType((*AccountInfo)(nil), "neutralservice.AccountInfo")
	proto.RegisterType((*Accounts)(nil), "neutralservice.Accounts")
	proto.RegisterMapType((map[string]*AccountInfo)(nil), "neutralservice.Accounts.AccountsEntry")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x6b, 0x13, 0x41,
	0x14, 0xc5, 0x99, 0x36, 0x4d, 0x93, 0x9b, 0x26, 0x96, 0x41, 0x65, 0xad, 0x20, 0x21, 0x42, 0x09,
	0x3e, 0x2c, 0x34, 0x15, 0xac, 0x3e, 0xd9, 0xa0, 0x0f, 0xc5, 0x97, 0x3a, 0xb1, 0xe0, 0xeb, 0x64,
	0xf6, 0x5a, 0xc6, 0x64, 0x67, 0xd6, 0xf9, 0x53, 0x9b, 0x8f, 0xe0, 0x83, 0xdf, 0xc3, 0x8f, 0x29,
	0xbb, 0x99, 0xec, 0x6e, 0xb6, 0xad, 0xf8, 0x76, 0x39, 0xf3, 0x3b, 0x67, 0x86, 0xc3, 0x1d, 0x18,
	0x70, 0x21, 0xb4, 0x57, 0xce, 0xc6, 0x99, 0xd1, 0x4e, 0xd3, 0x81, 0x42, 0xef, 0x0c, 0x5f, 0x5a,
	0x34, 0x37, 0x52, 0xe0, 0xd1, 0x81, 0xd0, 0x69, 0xaa, 0xd5, 0xfa, 0x74, 0xf4, 0x16, 0x1e, 0x5d,
	0x59, 0x34, 0xe7, 0x6b, 0xcf, 0x85, 0xfa, 0xa6, 0x29, 0x85, 0x96, 0xe2, 0x29, 0x46, 0x64, 0x48,
	0xc6, 0x5d, 0x56, 0xcc, 0xb9, 0xe6, 0x24, 0x9a, 0x68, 0x67, 0xad, 0xe5, 0xf3, 0xe8, 0x3d, 0x0c,
	0x82, 0x8d, 0xe1, 0x0f, 0x8f, 0xd6, 0xd1, 0x18, 0xda, 0xde, 0xa2, 0xb9, 0xf8, 0x50, 0x78, 0x7b,
	0x93, 0xa7, 0xf1, 0xf6, 0xdd, 0xf1, 0x55, 0x71, 0xca, 0x02, 0x35, 0xfa, 0x45, 0xe0, 0xf1, 0x4c,
	0x5e, 0x2b, 0x4c, 0x1a, 0x41, 0x6f, 0xa0, 0x6b, 0xe5, 0xb5, 0xe2, 0xce, 0x1b, 0x0c, 0x59, 0xcf,
	0x9a, 0x59, 0xb3, 0x0d, 0xc0, 0x2a, 0x96, 0x9e, 0xc1, 0xfe, 0x4f, 0xc3, 0xb3, 0x0c, 0x93, 0xe2,
	0xa9, 0xbd, 0xc9, 0x8b, 0xa6, 0x6d, 0xfb, 0x26, 0xb6, 0xc1, 0x47, 0xbf, 0x5b, 0xd0, 0x6b, 0xb4,
	0xe0, 0xbd, 0x4c, 0x36, 0x2d, 0xe4, 0xf3, 0x7d, 0x2d, 0x94, 0x6d, 0xed, 0xd6, 0xda, 0xaa, 0x7a,
	0x68, 0xfd, 0x4f, 0x0f, 0xf4, 0x35, 0x74, 0x33, 0x3f, 0x5f, 0x4a, 0xf1, 0x09, 0x57, 0xd1, 0xde,
	0xfd, 0x96, 0x4b, 0x3f, 0x5f, 0xe0, 0x8a, 0x55, 0x20, 0x3d, 0x85, 0xee, 0x5c, 0x26, 0xb3, 0xcc,
	0x20, 0x4f, 0xa2, 0x76, 0xe1, 0x7a, 0x72, 0xc7, 0x65, 0xa4, 0x40, 0x56, 0x71, 0xb9, 0x89, 0xdb,
	0x45, 0x30, 0xed, 0xff, 0xd3, 0x54, 0x72, 0xf4, 0x15, 0x1c, 0xe2, 0x6d, 0x26, 0x0d, 0x77, 0x52,
	0xab, 0xe9, 0x52, 0x8b, 0x85, 0x8d, 0x3a, 0x43, 0x32, 0xee, 0xb3, 0x3b, 0x3a, 0x3d, 0x86, 0x41,
	0xa5, 0x7d, 0x91, 0x29, 0x46, 0xdd, 0x21, 0x19, 0xb7, 0x58, 0x43, 0xcd, 0xb9, 0x54, 0xaa, 0xa9,
	0x4c, 0x3e, 0x7b, 0xae, 0x9c, 0x74, 0xab, 0x08, 0x86, 0x64, 0x4c, 0x58, 0x43, 0x2d, 0x38, 0x7e,
	0x5b, 0xe7, 0x7a, 0x81, 0xdb, 0x52, 0x43, 0xde, 0xb9, 0x5d, 0x94, 0xdc, 0x41, 0x99, 0x57, 0x53,
	0x43, 0x5e, 0x9d, 0xeb, 0x97, 0x79, 0x35, 0x75, 0xf4, 0x87, 0x40, 0x27, 0xec, 0x83, 0xa5, 0x53,
	0xe8, 0x6c, 0x7e, 0x55, 0x44, 0x86, 0xbb, 0xe3, 0xde, 0xe4, 0xf8, 0x81, 0xbd, 0xb2, 0xe5, 0xf0,
	0x51, 0x39, 0xb3, 0x62, 0xa5, 0xef, 0xe8, 0x2b, 0xf4, 0xb7, 0x8e, 0xe8, 0x21, 0xec, 0x2e, 0x70,
	0x15, 0x16, 0x2c, 0x1f, 0xe9, 0x09, 0xec, 0xdd, 0xf0, 0xa5, 0xc7, 0xb0, 0xbb, 0xcf, 0x1f, 0xb8,
	0x23, 0xdf, 0x4f, 0xb6, 0x26, 0xdf, 0xed, 0x9c, 0x91, 0xe9, 0x09, 0xbc, 0x14, 0x3a, 0xdd, 0xc0,
	0x99, 0xd1, 0xdf, 0x51, 0xb8, 0x78, 0x29, 0xe7, 0x71, 0x30, 0xda, 0xd8, 0x64, 0x62, 0x5a, 0x3e,
	0xe5, 0x92, 0xcc, 0xdb, 0xc5, 0xef, 0x3f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x94, 0x83, 0x23,
	0xc0, 0x2d, 0x04, 0x00, 0x00,
}
