// Code generated by protoc-gen-go. DO NOT EDIT.
// source: instruments.proto

package neutralservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SymbolAtExchange struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymbolAtExchange) Reset()         { *m = SymbolAtExchange{} }
func (m *SymbolAtExchange) String() string { return proto.CompactTextString(m) }
func (*SymbolAtExchange) ProtoMessage()    {}
func (*SymbolAtExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e1cbfd66e82bd, []int{0}
}

func (m *SymbolAtExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymbolAtExchange.Unmarshal(m, b)
}
func (m *SymbolAtExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymbolAtExchange.Marshal(b, m, deterministic)
}
func (m *SymbolAtExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymbolAtExchange.Merge(m, src)
}
func (m *SymbolAtExchange) XXX_Size() int {
	return xxx_messageInfo_SymbolAtExchange.Size(m)
}
func (m *SymbolAtExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_SymbolAtExchange.DiscardUnknown(m)
}

var xxx_messageInfo_SymbolAtExchange proto.InternalMessageInfo

func (m *SymbolAtExchange) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SymbolAtExchange) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type InstrumentDefinition struct {
	Issuer               string              `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	InstrumentID         *InstrumentID       `protobuf:"bytes,2,opt,name=instrumentID,proto3" json:"instrumentID,omitempty"`
	Decimals             uint32              `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	SymbolAtExchange     []*SymbolAtExchange `protobuf:"bytes,4,rep,name=symbolAtExchange,proto3" json:"symbolAtExchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InstrumentDefinition) Reset()         { *m = InstrumentDefinition{} }
func (m *InstrumentDefinition) String() string { return proto.CompactTextString(m) }
func (*InstrumentDefinition) ProtoMessage()    {}
func (*InstrumentDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e1cbfd66e82bd, []int{1}
}

func (m *InstrumentDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentDefinition.Unmarshal(m, b)
}
func (m *InstrumentDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentDefinition.Marshal(b, m, deterministic)
}
func (m *InstrumentDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentDefinition.Merge(m, src)
}
func (m *InstrumentDefinition) XXX_Size() int {
	return xxx_messageInfo_InstrumentDefinition.Size(m)
}
func (m *InstrumentDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentDefinition proto.InternalMessageInfo

func (m *InstrumentDefinition) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *InstrumentDefinition) GetInstrumentID() *InstrumentID {
	if m != nil {
		return m.InstrumentID
	}
	return nil
}

func (m *InstrumentDefinition) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *InstrumentDefinition) GetSymbolAtExchange() []*SymbolAtExchange {
	if m != nil {
		return m.SymbolAtExchange
	}
	return nil
}

type InstrumentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstrumentRequest) Reset()         { *m = InstrumentRequest{} }
func (m *InstrumentRequest) String() string { return proto.CompactTextString(m) }
func (*InstrumentRequest) ProtoMessage()    {}
func (*InstrumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e1cbfd66e82bd, []int{2}
}

func (m *InstrumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentRequest.Unmarshal(m, b)
}
func (m *InstrumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentRequest.Marshal(b, m, deterministic)
}
func (m *InstrumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentRequest.Merge(m, src)
}
func (m *InstrumentRequest) XXX_Size() int {
	return xxx_messageInfo_InstrumentRequest.Size(m)
}
func (m *InstrumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentRequest proto.InternalMessageInfo

type InstrumentResponse struct {
	InstrumentDefinitions []*InstrumentDefinition `protobuf:"bytes,1,rep,name=instrumentDefinitions,proto3" json:"instrumentDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *InstrumentResponse) Reset()         { *m = InstrumentResponse{} }
func (m *InstrumentResponse) String() string { return proto.CompactTextString(m) }
func (*InstrumentResponse) ProtoMessage()    {}
func (*InstrumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e1cbfd66e82bd, []int{3}
}

func (m *InstrumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentResponse.Unmarshal(m, b)
}
func (m *InstrumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentResponse.Marshal(b, m, deterministic)
}
func (m *InstrumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentResponse.Merge(m, src)
}
func (m *InstrumentResponse) XXX_Size() int {
	return xxx_messageInfo_InstrumentResponse.Size(m)
}
func (m *InstrumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentResponse proto.InternalMessageInfo

func (m *InstrumentResponse) GetInstrumentDefinitions() []*InstrumentDefinition {
	if m != nil {
		return m.InstrumentDefinitions
	}
	return nil
}

type SignedInstrumentResponse struct {
	Signature            *Signature          `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Wrapped              *InstrumentResponse `protobuf:"bytes,2,opt,name=wrapped,proto3" json:"wrapped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SignedInstrumentResponse) Reset()         { *m = SignedInstrumentResponse{} }
func (m *SignedInstrumentResponse) String() string { return proto.CompactTextString(m) }
func (*SignedInstrumentResponse) ProtoMessage()    {}
func (*SignedInstrumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e1cbfd66e82bd, []int{4}
}

func (m *SignedInstrumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedInstrumentResponse.Unmarshal(m, b)
}
func (m *SignedInstrumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedInstrumentResponse.Marshal(b, m, deterministic)
}
func (m *SignedInstrumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedInstrumentResponse.Merge(m, src)
}
func (m *SignedInstrumentResponse) XXX_Size() int {
	return xxx_messageInfo_SignedInstrumentResponse.Size(m)
}
func (m *SignedInstrumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedInstrumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignedInstrumentResponse proto.InternalMessageInfo

func (m *SignedInstrumentResponse) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedInstrumentResponse) GetWrapped() *InstrumentResponse {
	if m != nil {
		return m.Wrapped
	}
	return nil
}

func init() {
	proto.RegisterType((*SymbolAtExchange)(nil), "neutralservice.SymbolAtExchange")
	proto.RegisterType((*InstrumentDefinition)(nil), "neutralservice.InstrumentDefinition")
	proto.RegisterType((*InstrumentRequest)(nil), "neutralservice.InstrumentRequest")
	proto.RegisterType((*InstrumentResponse)(nil), "neutralservice.InstrumentResponse")
	proto.RegisterType((*SignedInstrumentResponse)(nil), "neutralservice.SignedInstrumentResponse")
}

func init() { proto.RegisterFile("instruments.proto", fileDescriptor_c06e1cbfd66e82bd) }

var fileDescriptor_c06e1cbfd66e82bd = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3b, 0x4f, 0xeb, 0x30,
	0x14, 0x56, 0x6e, 0xaf, 0x7a, 0x6f, 0x4f, 0x0b, 0xb4, 0xe6, 0xa1, 0x50, 0x31, 0x44, 0x81, 0xa1,
	0x53, 0x86, 0x32, 0xc0, 0xc0, 0x00, 0x55, 0x41, 0xaa, 0xc4, 0x50, 0xb9, 0x1b, 0x5b, 0x9a, 0x1e,
	0x8a, 0x51, 0x62, 0x1b, 0x1f, 0x87, 0xc7, 0xcf, 0xe0, 0xef, 0xf1, 0x6b, 0x50, 0xd3, 0xa4, 0xe9,
	0x73, 0x3c, 0xf6, 0xf7, 0xb4, 0x0f, 0xb4, 0x84, 0x24, 0x6b, 0xd2, 0x04, 0xa5, 0xa5, 0x40, 0x1b,
	0x65, 0x15, 0xdb, 0x97, 0x98, 0x5a, 0x13, 0xc6, 0x84, 0xe6, 0x5d, 0x44, 0xd8, 0x6e, 0x44, 0x2a,
	0x49, 0x94, 0x9c, 0xdf, 0xfa, 0x0f, 0xd0, 0x1c, 0x7d, 0x25, 0x63, 0x15, 0xdf, 0xd9, 0xfb, 0xcf,
	0xe8, 0x25, 0x94, 0x53, 0x64, 0x27, 0x50, 0xa5, 0xec, 0xcc, 0x75, 0x3c, 0xa7, 0x53, 0xe3, 0xf9,
	0xc4, 0xda, 0xf0, 0x1f, 0x73, 0x8c, 0xfb, 0x27, 0xbb, 0x59, 0xcc, 0xfe, 0x8f, 0x03, 0x47, 0x83,
	0x85, 0x77, 0x1f, 0x9f, 0x85, 0x14, 0x56, 0x28, 0x39, 0x13, 0x13, 0x44, 0x29, 0x9a, 0x42, 0x6c,
	0x3e, 0xb1, 0x5b, 0x68, 0x94, 0x59, 0x07, 0xfd, 0x4c, 0xb0, 0xde, 0x3d, 0x0b, 0x56, 0xd3, 0x06,
	0x83, 0x25, 0x0c, 0x5f, 0x61, 0xcc, 0xe2, 0x4c, 0x30, 0x12, 0x49, 0x18, 0x93, 0x5b, 0xf1, 0x9c,
	0xce, 0x1e, 0x5f, 0xcc, 0xec, 0x11, 0x9a, 0xb4, 0x56, 0xcb, 0xfd, 0xeb, 0x55, 0x3a, 0xf5, 0xae,
	0xb7, 0xee, 0xb0, 0x5e, 0x9f, 0x6f, 0x30, 0xfd, 0x43, 0x68, 0x95, 0x39, 0x38, 0xbe, 0xa5, 0x48,
	0xd6, 0xd7, 0xc0, 0x96, 0x0f, 0x49, 0x2b, 0x49, 0xc8, 0x9e, 0xe0, 0x58, 0x6c, 0x79, 0x06, 0x72,
	0x9d, 0xcc, 0xfd, 0x62, 0x77, 0xbf, 0x12, 0xcc, 0xb7, 0x4b, 0xf8, 0xdf, 0x0e, 0xb8, 0x23, 0x31,
	0x95, 0x38, 0xd9, 0x62, 0x7c, 0x05, 0x35, 0x12, 0x53, 0x19, 0xda, 0xd4, 0x60, 0xf6, 0xd4, 0xf5,
	0xee, 0xe9, 0x46, 0xd5, 0x02, 0xc0, 0x4b, 0x2c, 0xbb, 0x81, 0x7f, 0x1f, 0x26, 0xd4, 0x1a, 0x27,
	0xf9, 0x1f, 0xf8, 0xbb, 0x33, 0x16, 0x6e, 0xbc, 0xa0, 0xf4, 0xae, 0xe1, 0x3c, 0x52, 0x49, 0xc1,
	0xd0, 0x46, 0xbd, 0x62, 0x64, 0x83, 0x58, 0x8c, 0x83, 0x9c, 0x4d, 0x81, 0xd1, 0x51, 0xef, 0xa0,
	0xd4, 0x18, 0xce, 0xf6, 0x6e, 0xe8, 0x8c, 0xab, 0xd9, 0x02, 0x5e, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x68, 0xfe, 0x67, 0xb3, 0x02, 0x00, 0x00,
}
